NamrataKalyani/Controllers/BillingController.cs
using Dapper;
using NamrataKalyani.CustomAttribute;
using NamrataKalyani.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace NamrataKalyani.Controllers
{
    [Authorize]
    [SessionTimeoutAttribute]
    public class BillingController : Controller
    {
        // GET: Billing

        int UserId;
        public BillingController()
        {
            if (System.Web.HttpContext.Current.Session["UserId"] != null)
            {
                UserId = Convert.ToInt32(System.Web.HttpContext.Current.Session["UserId"]);
            }
        }

        public ActionResult GetBillingInfo(int? BillId, string BeginDate, string Enddate)
        {

            var dlist = RetuningData.ReturnigList<PatientInfoModel>("usp_getReportsByBill", null);
            ViewBag.PatientList = new SelectList(dlist, "PId", "PName");
            var param = new DynamicParameters();
            if (Request.QueryString["id"] != null)
            {
                param.Add("@BillId", Request.QueryString["id"]);
            }
            else
            {
                param.Add("@BillId", BillId);
            }
            param.Add("@BeginDate", BeginDate);
            param.Add("@EndDate", Enddate);
            if (string.IsNullOrEmpty(System.Web.HttpContext.Current.Session["RoleId"].ToString()))
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                param.Add("@RoleId", System.Web.HttpContext.Current.Session["RoleId"]);

            }
            var Bill = RetuningData.ReturnigList<_BilIingInfoModel>("getReports_test", param);

            return View(Bill);
        }

        public ActionResult UpdateBillingInfo(int? id, string BeginDate, string Enddate)
        {
            var param = new DynamicParameters();
            param.Add("@BillId", id);
            param.Add("@BeginDate", BeginDate);
            param.Add("@EndDate", Enddate);
            var Bill = RetuningData.ReturnigList<_BilIingInfoModel>("getReports_test", param).SingleOrDefault();

            return View(Bill);
        }

        [HttpPost]
        public ActionResult UpdateBillingInfo(_BilIingInfoModel Bill)
        {
            int result = 0, roleId;
            if (!String.IsNullOrEmpty(System.Web.HttpContext.Current.Session["RoleId"].ToString()))
            {
                roleId = Convert.ToInt32(System.Web.HttpContext.Current.Session["RoleId"]);
            }
            else
            {
                return RedirectToAction("login","login");
            }
            var param = new DynamicParameters();
            param.Add("@BillId", Bill.BillId);
            param.Add("@Amount", Bill.Amount);
            param.Add("@Discount", Bill.Discount);
            param.Add("@Expenses", Bill.Expenses);
            param.Add("@Due", Bill.Due);
            param.Add("@ReferalAmount", Bill.ReferalAmount);
            param.Add("@Status", Bill.Status);
            param.Add("@ReferalPercentage", Bill.ReferalPercentage);
            param.Add("@UpdatedBy", UserId);
            result = RetuningData.AddOrSave<int>("usp_UpdateBilling", param);

            if (result > 0 && roleId==1)
            {
                return RedirectToAction("GetBillingInfo");
            }
            else
            {
                return RedirectToAction("GetBillingInfo",new {BillId= Bill.BillId });
            }
        }
    }
}

NamrataKalyani/Controllers/ReferalDoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using System.Data;
using System.Data.SqlClient;
using PagedList;
using PagedList.Mvc;
using NamrataKalyani.Models;
using NamrataKalyani.CustomAttribute;

namespace NamrataKalyani.Controllers
{
    [Authorize]
    [SessionTimeoutAttribute]
    public class ReferalDoctorController : Controller
    {
        // GET: ReferalDoctor
        // GET: ReferDoc
        int UserId;
        public ReferalDoctorController()
        {
            if (System.Web.HttpContext.Current.Session["UserId"] != null)
            {
                UserId = Convert.ToInt32(System.Web.HttpContext.Current.Session["UserId"]);
            }
        }
        public ActionResult ReferDocIndex(int? page)
        {
            var rd = RetuningData.ReturnigList<ReferalDoctorModel>("usp_getReferDoc", null).ToPagedList(page ?? 1, 5);

            return View(rd);
        }


        public ActionResult CreateRecord()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateRecord(ReferalDoctorModel rdm)
        {
            var param = new DynamicParameters();
    
            param.Add("@DoctorName", rdm.DoctorName);
            param.Add("@CreatedBy", UserId);
            param.Add("@UpdatedBy", UserId);

            int i = RetuningData.AddOrSave<int>("uspAddDoctor", param);
            if (i > 0)
            {

                return RedirectToAction("ReferDocIndex");
            }

            return View();
        }
        public ActionResult EditRecord(int? id)
        {
            var param = new DynamicParameters();
            param.Add("@Rid", id);
            var rdm = RetuningData.ReturnigList<ReferalDoctorModel>("sp_ReferDoctorById", param).SingleOrDefault();
            return View(rdm);

        }


        [HttpPost]
        public ActionResult EditRecord(ReferalDoctorModel rdm)
        {
            var param = new DynamicParameters();
            param.Add("@DocId", rdm.DocId);
            param.Add("@DoctorName", rdm.DoctorName);
            //param.Add("@Email", rdm.Email);
            //param.Add("@Mobile", rdm.Mobile);
             param.Add("@UpdatedBy", UserId);
          

            int i = RetuningData.AddOrSave<int>("sp_UpdateReferDoctorById", param);

            if (i > 0)
            {
                return RedirectToAction("ReferDocIndex");
            }
            return View();
        }


        public ActionResult DeleteRecord(int? id)
        {

            var param = new DynamicParameters();
            param.Add("@Rid", id);
            var rm = RetuningData.ReturnigList<ReferalDoctorModel>("sp_ReferDoctorById", param).SingleOrDefault();
            return View(rm);
        }

        [HttpPost]
        public ActionResult DeleteRecord(ReferalDoctorModel rdm)
        {

            var param = new DynamicParameters();

            param.Add("@Rid", rdm.DocId);
            var num = RetuningData.ReturnigList<ReferalDoctorModel>("DeleteReferalDocById", param).SingleOrDefault();


            if (num != null)
            {
                ViewBag.msg = "Record Deleted";
                return RedirectToAction("ReferDocIndex");
            }

            return RedirectToAction("ReferDocIndex");
        }
    }
}

NamrataKalyani/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NamrataKalyani.Models;
using Dapper;
using System.Data;
using System.Data.SqlClient;
using PagedList;
using PagedList.Mvc;
using NamrataKalyani.CustomAttribute;

namespace NamrataKalyani.Controllers
{
    [Authorize]
    [SessionTimeoutAttribute]
    public class ReportsController : Controller
    {
        int UserId;
        public ReportsController()
        {
            if (System.Web.HttpContext.Current.Session["UserId"] != null)
            {
                UserId = Convert.ToInt32(System.Web.HttpContext.Current.Session["UserId"]);
            }
        }

        // GET: Reports
        public ActionResult Index(int? page)        {            var rm = RetuningData.ReturnigList<ReportModel>("sp_getReports", null).ToPagedList(page ?? 1, 10);
            return View(rm);        }        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ReportModel rem)
        {
            var param = new DynamicParameters();
            param.Add("@RName", rem.ReportType);
            param.Add("@Description", rem.Description);
            param.Add("@ShortName", rem.ShortName);
            param.Add("@CreatedBy", UserId);
            param.Add("@UpdatedBy", UserId);

            int i = RetuningData.AddOrSave<int>("sp_SaveReport", param);
            if (i > 0)
            {

                return RedirectToAction("index");
            }

            return View();
        }

        public ActionResult Edit(int? id)
        {

            var param = new DynamicParameters();
            param.Add("@Rid", id);
            var rm = RetuningData.ReturnigList<ReportModel>("sp_ReportById", param).SingleOrDefault();


            return View(rm);
        }

        [HttpPost]        public ActionResult Edit(ReportModel rm)        {            var param = new DynamicParameters();            param.Add("@Rid", rm.Id);            param.Add("@RName", rm.ReportType);            param.Add("@Description", rm.Description);            param.Add("@ShortName", rm.ShortName);            param.Add("@UpdatedBy", UserId );            param.Add("@UpdatedOn", DateTime.Now);            int i = RetuningData.AddOrSave<int>("usp_UpdateReportById", param);            if (i > 0)            {                return RedirectToAction("Index");            }            return View();        }


        public ActionResult Delete(int? id)
        {

            var param = new DynamicParameters();
            param.Add("@Rid", id);
            var rm = RetuningData.ReturnigList<ReportModel>("sp_ReportById", param).SingleOrDefault();
            return View(rm);
        }

        [HttpPost]
        public ActionResult Delete(ReportModel rm)
        {

            var param = new DynamicParameters();

            param.Add("@Rid", rm.Id);
            var num = RetuningData.ReturnigList<ReportModel>("sp_DeleteReportById", param).SingleOrDefault();


            if (num != null)
            {
                ViewBag.msg = "Record Deleted";
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        //public ActionResult Search()
        //{
        //    return View();
        //}

        //[HttpPost]
        //public ActionResult Search(ReportModel rm)
        //{
        //    var param = new DynamicParameters();
        //    // param.Add("@Pid", Session["Pid"]);
        //    //param.Add("@Date", cbrm.date);
        //    param.Add("@Rname", rm.ReportType);
        //    //int i = RetuningData.AddOrSave<int>("Dashborad", param);
        //    var i = RetuningData.ReturnigList<ReportModel>("uspGetReportByName", param);
        //    if (i != null)
        //    {

        //                        return View(i);
        //    }
        //    else
        //    {
        //        return View();
        //    }

        //}

    }

}

NamrataKalyani/Views/Shared/PatientInfoExistingUser.cshtml
@model NamrataKalyani.Models.PatientInfoModel
<script>
    function DisableObjects(rbEUser) {
        if (rbEUser.checked == true) {
            $('#pname').attr("disabled", "true");
            $('#age').attr("disabled", "true");
            $('#gender').attr("disabled", "true");
            $('#gender').attr("disabled", "true");
            //document.getElementById(pname).disabled = true;
            //document.getElementById(age).disabled = true;
            //document.getElementById(gender).disabled = true;
            $('#search').css('display', 'block');
        }

    }
    function EnableObjects(rbNUser) {
        if (rbNUser.checked == true) {
            $('#pname').removeAttr("disabled");
            $('#age').removeAttr("disabled");
            $('#gender').removeAttr("disabled");
            $('#gender').removeAttr("disabled");
            $('#search').css('display', 'none');

        }
    }
</script>


@using (Html.BeginForm("PatientInfo1", "Doc", FormMethod.Post))
{
    <div class="container">
        <div class="panel panel-primary">
            <div class="panel-heading">Panel with panel-primary class</div>
            <div class="panel-body">
            <div class="form-group">
                <div class="form-group">
                    @Html.Label("User Type", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4" style="margin-bottom:2px">
                        @Html.RadioButton("User Type", "Existing User", true, new { Onclick = "DisableObjects(this)" }) Existing User

                        @Html.RadioButton("User Type", "New User", new { Onclick = "EnableObjects(this)" })  New User

                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.mobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-4">
                        @Html.TextBoxFor(model => model.mobileNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.mobileNo, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-success" id="search">Search</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
}

NamrataKalyani/Views/Shared/_CreateBill.cshtml
@model List<NamrataKalyani.Models._BilIingInfoModel>
@{
    ViewBag.Title = "GetBillingInfo";
}

<h2>GetBillingInfo</h2>

<div class="container">
    @using (Html.BeginForm("UpdateBillingInfo", "Billing", FormMethod.Post))
    {
        <div class="col-md-4" style="margin-bottom:4px">
            @Html.DropDownList("PatientList", null, "Select Patient", new { @class = "form-control" })
        </div>
        <input type="submit" value="Search" class="btn-primary" />
    }

    @using (Html.BeginForm("UpdateBillingInfo", "Billing", FormMethod.Post))
    {
        <table class="table table-condensed table-hover" id="mytable">
            <tr>
                <th>Report Name</th>
                <th>Amount</th>
                <th>Discount(Rs)</th>
                <th>Expenses</th>
                <th>Referal Amount(%)</th>
                <th>Investment</th>
                <th>Status</th>
                <th>Total</th>
            </tr>

            <tbody>
                @for (int i = 0; i < Model.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.HiddenFor(m => m[i].ReportId, new { @class = "form-control amount" })
                            @Html.HiddenFor(m => m[i].PId, new { @class = "form-control amount" })
                            @Model[i].ReportName
                        </td>
                        <td>
                            @Html.TextBoxFor(m => m[i].Amount, new { @class = "form-control amount" })
                        </td>
                        <td>
                            @Html.TextBoxFor(m => m[i].Discount, new { @class = "form-control discount" })
                        </td>
                        <td>
                            @Html.TextBoxFor(m => m[i].Expenses, new { @class = "form-control expenses" })
                        </td>
                        <td>
                            @Html.TextBoxFor(m => m[i].ReferalAmount, new { @class = "form-control referalAmount" })
                        </td>
                        <td>
                            @Html.TextBoxFor(m => m[i].Investment, new { @class = "form-control investment" })
                        </td>
                        <td>
                            @Html.DropDownListFor(m => m[i].Status, new List<SelectListItem>() {

                          new SelectListItem {Text="Paid",Value="1"},
                          new SelectListItem {Text="Pending",Value="0"},
                      })
                        </td>
                        <td>
                            @Html.TextBoxFor(m => m[i].Total_Amount, new { @class = "form-control total_amount" })
                        </td>

                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><input type="text" class="grdtot" value="" name="" /></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                        <input type="submit" class="btn btn-success" value="Save" />
                    </td>
                    <td></td>
                    <td></td>

                </tr>
            </tfoot>
        </table>
    }
</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>


    function percentage(num, per) {
        return (num / 100) * per;
    }


        $(function () {
            $('.grdtot,.total_amount').prop('readonly', true);
            var $tblrows = $("#mytable tbody tr");

            $tblrows.each(function (index) {
                var $tblrow = $(this);

                $tblrow.find('input[type=text]').on('change', function () {

                    var amt = $tblrow.find("input[type=text].amount").val();
                    var disc = $tblrow.find("input[type=text].discount").val();
                    var exp = $tblrow.find("input[type=text].expenses").val();
                    var refamt = amt * $tblrow.find("input[type=text].referalAmount").val() / 100;
                    var inv = $tblrow.find("input[type=text].investment").val();
                    var subTotal = parseFloat(amt) - parseFloat(disc) - parseFloat(exp) - parseFloat(refamt) - parseFloat(inv);

                    if (!isNaN(subTotal)) {

                        $tblrow.find('.total_amount').val(subTotal.toFixed(2));
                        var grandTotal = 0;

                        $(".total_amount").each(function () {
                            var stval = parseFloat($(this).val());
                            grandTotal += isNaN(stval) ? 0 : stval;
                        });

                        $('.grdtot').val(grandTotal.toFixed(2));
                    }
                });
            });
        });
</script>

NamrataKalyani/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Report", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
       
        @*@{
            Html.RenderPartial("_PatientDetails");
        }*@
       
        @RenderBody()
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NamrataKalyani/Views/Shared/_LayoutPartialView.cshtml
@{
    ViewBag.Title = "_LayoutPartialView";
}

 


<style>
    th, td {
        white-space: nowrap;
    }
</style>
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.11.2/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.0.1/css/buttons.dataTables.min.css" />




<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.2/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.0.1/js/buttons.print.min.js"></script>
<script>

    $(document).ready(function () {
        $('#mytable').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copyHtml5',
                'excelHtml5',
                'csvHtml5',
                'pdfHtml5'
            ]
        });
    });
    </script>

NamrataKalyani/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Akber Diagnostic Center</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
    <script src="~/Scripts/bootstrap.bundle.min.js"></script> 
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" /> 
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.0.1/css/buttons.dataTables.min.css" />
    <link href="~/Content/Slider.css" rel="stylesheet" />
    <script src="~/Scripts/Slider.js"></script>
    <link href="~/Content/boxicons.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   
    <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}

    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @@media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;}
    }
    </style>
</head>
<body id="body-pd">

    <header class="header" id="header">
        <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
    </header>
    <div class="l-navbar" id="nav-bar">
        <nav class="nav">
            <div>
                <a href="#" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span class="nav_logo-name">Home</span> </a>
                <div>
                    
                    <a href="@Url.Action("PatientInfo","doc",null)" class="nav_link">
                        <i class='bx bx-user nav_icon'></i>
                        <span class="nav_name">New Patient</span>
                    </a>
                    <a href="@Url.Action("index","Reports",null)" class="nav_link">
                        <i class='bx bx-user nav_icon'></i>
                        <span class="nav_name">Report</span>
                    </a> <a href="@Url.Action("ReferDocIndex","ReferalDoctor",null)" class="nav_link">
                        <i class='bx bx-message-square-detail nav_icon'></i> <span class="nav_name">Doctor</span>
                    </a>
                    <a href="@Url.Action("GetBillingInfo","Billing",null)" class="nav_link">
                        <i class='bx bx-bookmark nav_icon'></i> <span class="nav_name">Bill</span>
                    </a>

                </div>
            </div>
           @* <a href="#" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">SignOut</span> </a>*@
        </nav>
    </div>

    <div class="height-100 bg-light">
        @RenderBody()
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NamrataKalyani/Views/Shared/_PatientDetails.cshtml
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<style>
    /* Remove the navbar's default margin-bottom and rounded borders */
    .navbar {
        margin-bottom: 0;
        border-radius: 0;
    }

    /* Add a gray background color and some padding to the footer */
    footer {
        background-color: #f2f2f2;
        padding: 25px;
    }

    .carousel-inner img {
        width: 100%; /* Set width to 100% */
        margin: auto;
        min-height: 200px;
    }

    /* Hide the carousel text when the screen is less than 600 pixels wide */
    @@media (max-width: 600px) {
        .carousel-caption {
            display: none;
        }
    }
</style>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Logo</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Projects</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>
        </div>
    </div>
</nav>